FROM openjdk:17-jdk-slim

ENV APP_HOME=/usr/app/
WORKDIR $APP_HOME

COPY ./fooding-api/build/libs/*.jar application.jar

ARG WEBHOOK_SLACK_URL
ARG API_AUTHORIZATION_TOKEN
ARG JWT_SECRET_KEY
ARG DB_URL
ARG DB_USER
ARG DB_PASSWORD
ARG MAIL_SEND_USERNAME
ARG MAIL_SEND_PASSWORD
ARG MAIL_SEND_FROM_ADDRESS
ARG SPRING_PROFILES_ACTIVE
ARG UPLOAD_PATH
ARG STORAGE_API_URL
ARG STORAGE_API_TOKEN
ARG STORAGE_API_BUCKET_ID
ARG JPA_DDL_AUTO

ENV WEBHOOK_SLACK_URL=$WEBHOOK_SLACK_URL
ENV API_AUTHORIZATION_TOKEN=$API_AUTHORIZATION_TOKEN
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV DB_URL=$DB_URL
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV MAIL_SEND_USERNAME=$MAIL_SEND_USERNAME
ENV MAIL_SEND_PASSWORD=$MAIL_SEND_PASSWORD
ENV MAIL_SEND_FROM_ADDRESS=$MAIL_SEND_FROM_ADDRESS
ENV SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
ENV UPLOAD_PATH=$UPLOAD_PATH
ENV STORAGE_API_URL=$STORAGE_API_URL
ENV STORAGE_API_TOKEN=$STORAGE_API_TOKEN
ENV STORAGE_API_BUCKET_ID=$STORAGE_API_BUCKET_ID
ENV JPA_DDL_AUTO=$JPA_DDL_AUTO

EXPOSE 8080

CMD ["java", "-jar", "application.jar"]