version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: fooding-mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=fooding
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: fooding-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=1234
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: fooding-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=${ES_SERVICE_TOKEN}
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk

  redis:
    image: redis:7-alpine
    container_name: fooding-redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Seoul
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass 1234

  mongodb:
    image: mongo:6
    container_name: fooding-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    volumes:
      - ./mongo/init:/docker-entrypoint-initdb.d
      - mongo_data:/data/db

volumes:
  esdata: {}
  mongo_data:
  redis_data:
networks:
  elk: {}
