version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: fooding-mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    ports:
      - 3309:3306
    environment:
      - MYSQL_DATABASE=fooding
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
  redis:
    image: redis:7-alpine
    container_name: fooding-redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Seoul
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass 1234
volumes:
  redis_data:
