FROM openjdk:17-jdk-slim

ENV APP_HOME=/usr/app/
WORKDIR $APP_HOME

COPY ./fooding-api/build/libs/*.jar application.jar

ARG WEBHOOK_SLACK_URL
ARG API_AUTHORIZATION_TOKEN
ARG JWT_SECRET_KEY
ARG MONGODB_URI
ARG DB_URL
ARG DB_USER
ARG DB_PASSWORD
ARG MAIL_SEND_USERNAME
ARG MAIL_SEND_PASSWORD
ARG MAIL_SEND_FROM_ADDRESS
ARG SPRING_PROFILES_ACTIVE
ARG UPLOAD_PATH
ARG STORAGE_API_URL
ARG STORAGE_API_TOKEN
ARG STORAGE_API_BUCKET_ID
ARG JPA_DDL_AUTO
ARG KAKAO_MAP_API_KEY
ARG KAKAO_MAP_API_URL
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG REDIS_DATABASE
ARG ELASTIC_SEARCH_URIS
ARG ELASTIC_SEARCH_USERNAME
ARG ELASTIC_SEARCH_PASSWORD

ENV WEBHOOK_SLACK_URL=$WEBHOOK_SLACK_URL
ENV API_AUTHORIZATION_TOKEN=$API_AUTHORIZATION_TOKEN
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV MONGODB_URI=$MONGODB_URI
ENV DB_URL=$DB_URL
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV MAIL_SEND_USERNAME=$MAIL_SEND_USERNAME
ENV MAIL_SEND_PASSWORD=$MAIL_SEND_PASSWORD
ENV MAIL_SEND_FROM_ADDRESS=$MAIL_SEND_FROM_ADDRESS
ENV SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
ENV UPLOAD_PATH=$UPLOAD_PATH
ENV STORAGE_API_URL=$STORAGE_API_URL
ENV STORAGE_API_TOKEN=$STORAGE_API_TOKEN
ENV STORAGE_API_BUCKET_ID=$STORAGE_API_BUCKET_ID
ENV JPA_DDL_AUTO=$JPA_DDL_AUTO
ENV KAKAO_MAP_API_KEY=$KAKAO_MAP_API_KEY
ENV KAKAO_MAP_API_URL=$KAKAO_MAP_API_URL
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ENV REDIS_DATABASE=$REDIS_DATABASE
ENV ELASTIC_SEARCH_URIS=$ELASTIC_SEARCH_URIS
ENV ELASTIC_SEARCH_USERNAME=$ELASTIC_SEARCH_USERNAME
ENV ELASTIC_SEARCH_PASSWORD=$ELASTIC_SEARCH_PASSWORD

EXPOSE 8080

CMD ["java", "-jar", "application.jar"]
