spring:
  config:
    activate:
      on-profile: local

  web:
    resources:
      add-mappings: false


  elasticsearch:
    uris: http://localhost:9200
    key: ${ELASTIC_SEARCH_KEY:}

  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/fooding?authSource=admin
      repositories:
        enabled: false
    redis:
      host: localhost
      port: 6379
      password: 1234
      database: 0
      repositories:
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3308/fooding?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret-key: KECHLtOh6ohqn1ucwQF0g9Ih1wbOjfJQ7EKMmfwZ1BmGtahQeeUOUA1JyZykdonF
  access:
    expiration: 604800000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh

springdoc:
  swagger-ui:
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /api-docs
  packages-to-exclude: /im/fooding/app/controller

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: DEBUG

        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    org.apache.kafka: INFO
    org.apache.kafka.clients.producer.ProducerConfig: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN

webhook:
  slack:
    url: ${WEBHOOK_SLACK_URL:}

email:
  smtp:
    host: smtp.gmail.com
    port: 587
  username: foodinghelper@fooding.im
  password: kzptuibhpdhlgpnb

message:
  sender: 02-1234-5678

auth:
  google:
    client-id: 88628206428-0m206hm81hfff14e5v6d5tgsmbnrbo9g.apps.googleusercontent.com
    client-secret: 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
    token-uri: https://oauth2.googleapis.com/token
    userinfo-uri: https://www.googleapis.com/oauth2/v2/userinfo

  kakao:
    restapi-key: f9ef71c243f291c800012839d6ad7340
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

  naver:
    client-id: uuQR8vP5VQLKCdaaxQB4
    client-secret: giFLLT7_aF
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me

  apple:
    client-id: im.fooding.loginservice
    team-id: 4TS88K9HKJ
    key-id: 4PPY69KNW8
    private-key: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrHlqh7uGlOTNbxyBSeyyZ4JyLKNMDboPO+K4he/6URKgCgYIKoZIzj0DAQehRANCAASN1R+nHzVoAbh7kRGG4GBdlOAqZTWsvC4AaWjQl2osHTB7Vu2ctjTvKJTD6Col9dCt4eFTPSQyMX+7ezJyucy2
    token-uri: https://appleid.apple.com/auth/token

storage:
  api:
    bucket-id: ${STORAGE_API_BUCKET_ID:}
    token: ${STORAGE_API_TOKEN:}

map:
  kakao:
    api-key: b3ad5d14b4171350a56dac59bf037bd7
    url: https://dapi.kakao.com/v2/local

#server:
#  port: 8080
#  ssl:
#    key-store: classpath:/keystore/keystore.p12
#    key-store-password: password
#    key-store-type: PKCS12

# Prometheus 설정 (로컬 환경)
management:
  server:
    port: 8081
    address: 0.0.0.0
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  health:
    elasticsearch:
      enabled: false

cache:
  type: none  # Redis 캐시 비활성화
kafka:
  internal:
    topic: fooding.event.internal.local
    groupId: fooding-event-internal-local
  consumer:
    enabled: false  # Kafka 소비자 비활성화
#kafka:
#  internal:
#    topic: fooding.event.internal.local
#    groupId: fooding-event-internal-local
