spring:
  config:
    activate:
      on-profile: local

  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:mysql://localhost:3308/fooding?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

jwt:
  secret-key: KECHLtOh6ohqn1ucwQF0g9Ih1wbOjfJQ7EKMmfwZ1BmGtahQeeUOUA1JyZykdonF
  access:
    expiration: 604800000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh

springdoc:
  api-docs:
    path: /api-docs
  packages-to-exclude: /im/fooding/app/controller

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: DEBUG

        type:
          descriptor:
            sql:
              BasicBinder: TRACE

webhook:
  slack:
    url: ${WEBHOOK_SLACK_URL}

message:
  sender: 02-1234-5678

auth:
  google:
    client-id: 88628206428-0m206hm81hfff14e5v6d5tgsmbnrbo9g.apps.googleusercontent.com
    client-secret: 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
    token-uri: https://oauth2.googleapis.com/token
    userinfo-uri: https://www.googleapis.com/oauth2/v2/userinfo
    redirect-uri: http://localhost:8080/user/auth/google/token

  kakao:
    restapi-key: f9ef71c243f291c800012839d6ad7340
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    redirect-uri: http://localhost:8080/user/auth/kakao/token

  naver:
    client-id: uuQR8vP5VQLKCdaaxQB4
    client-secret: giFLLT7_aF
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
    redirect-uri: http://localhost:8080/user/auth/naver/token

  apple:
    client-id: im.fooding.loginservice
    team-id: 4TS88K9HKJ
    key-id: 4PPY69KNW8
    private-key: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrHlqh7uGlOTNbxyBSeyyZ4JyLKNMDboPO+K4he/6URKgCgYIKoZIzj0DAQehRANCAASN1R+nHzVoAbh7kRGG4GBdlOAqZTWsvC4AaWjQl2osHTB7Vu2ctjTvKJTD6Col9dCt4eFTPSQyMX+7ezJyucy2
    token-uri: https://appleid.apple.com/auth/token
    redirect-uri: https://localhost.com:8080/user/auth/apple/token

storage:
  base-uri: ${STORAGE_BASE_URI}
  bucket-id: ${STORAGE_BUCKET_ID}
  access-token: ${STORAGE_ACCESS_TOKEN}

#server:
#  port: 8080
#  ssl:
#    key-store: classpath:/keystore/keystore.p12
#    key-store-password: password
#    key-store-type: PKCS12
