spring:
  config:
    activate:
      on-profile: "stage"

  web:
    resources:
      add-mappings: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USER:fooding}
    password: ${DB_PASSWORD:fooding}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: ${FORMAT_SQL:true}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:1000MB}
      max-request-size: ${MAX_REQUEST_SIZE:1000MB}

jwt:
  secretKey: ${JWT_SECRET_KEY:OxJyMRYZufUrGdBXpDyeLoTj2fbLu2XmHPPJMwdGsv5xcZvUXi}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION:604800000}
    header: ${JWT_ACCESS_HEADER:Authorization}

  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION:1209600000}
    header: ${JWT_REFRESH_HEADER:Authorization-refresh}

springdoc:
  api-docs:
    path: ${SPRINGDOC_PATH:/api-docs}
  packages-to-exclude: ${SPRINGDOC_EXCLUDE_PACKAGES:/im/fooding/app/controller}

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: ${LOG_LEVEL_JDBC_BIND:trace}
        SQL: ${LOG_LEVEL_SQL:DEBUG}
        type:
          descriptor:
            sql:
              BasicBinder: ${LOG_LEVEL_SQL_BINDER:TRACE}

webhook:
  slack:
    url: https://hooks.slack.com/services/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

message:
  sender: 02-1234-5678

auth:
  google:
    client-id: 88628206428-0m206hm81hfff14e5v6d5tgsmbnrbo9g.apps.googleusercontent.com
    client-secret: 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
    token-uri: https://oauth2.googleapis.com/token
    userinfo-uri: https://www.googleapis.com/oauth2/v2/userinfo
    redirect-uri: https://api-stage.fooding.im/user/auth/google/token

  kakao:
    restapi-key: f9ef71c243f291c800012839d6ad7340
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    redirect-uri: https://api-stage.fooding.im/user/auth/kakao/token

  naver:
    client-id: uuQR8vP5VQLKCdaaxQB4
    client-secret: giFLLT7_aF
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
    redirect-uri: https://api-stage.fooding.im/user/auth/naver/token

  apple:
    client-id: ""
    client-secret: ""
    token-uri: ""
    user-info-uri: ""
    redirect-uri: https://api-stage.fooding.im/auth/social-login/apple/token
