spring:
  config:
    activate:
      on-profile: local

  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:mysql://localhost:3308/fooding?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

jwt:
  secretKey: OxJyMRYZufUrGdBXpDyeLoTj2fbLu2XmHPPJMwdGsv5xcZvUXi
  access:
    expiration: 604800000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh

springdoc:
  api-docs:
    path: /api-docs
  packages-to-exclude: /im/fooding/app/controller

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: DEBUG

        type:
          descriptor:
            sql:
              BasicBinder: TRACE

webhook:
  slack:
    url: https://hooks.slack.com/services/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

message:
  sender: 02-1234-5678

auth:
  google:
    client-id: 88628206428-0m206hm81hfff14e5v6d5tgsmbnrbo9g.apps.googleusercontent.com
    client-secret: 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
    token-uri: https://oauth2.googleapis.com/token
    userinfo-uri: https://www.googleapis.com/oauth2/v2/userinfo
    redirect-uri: http://localhost:8080/user/auth/google/token

  kakao:
    restapi-key: f9ef71c243f291c800012839d6ad7340
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    redirect-uri: http://localhost:8080/user/auth/kakao/token

  naver:
    client-id: uuQR8vP5VQLKCdaaxQB4
    client-secret: giFLLT7_aF
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
    redirect-uri: http://localhost:8080/user/auth/naver/token

  apple:
    client-id: ""
    client-secret: ""
    token-uri: ""
    user-info-uri: ""
    redirect-uri: http://localhost:8080/user/auth/apple/token
