spring:
  config:
    activate:
      on-profile: "prod"

  web:
    resources:
      add-mappings: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USER:fooding}
    password: ${DB_PASSWORD:fooding}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: ${FORMAT_SQL:true}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:1000MB}
      max-request-size: ${MAX_REQUEST_SIZE:1000MB}

jwt:
  secret-key: ${JWT_SECRET_KEY:KECHLtOh6ohqn1ucwQF0g9Ih1wbOjfJQ7EKMmfwZ1BmGtahQeeUOUA1JyZykdonF}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION:604800000}
    header: ${JWT_ACCESS_HEADER:Authorization}

  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION:1209600000}
    header: ${JWT_REFRESH_HEADER:Authorization-refresh}

springdoc:
  api-docs:
    path: ${SPRINGDOC_PATH:/api-docs}
  packages-to-exclude: ${SPRINGDOC_EXCLUDE_PACKAGES:/im/fooding/app/controller}

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: ${LOG_LEVEL_JDBC_BIND:trace}
        SQL: ${LOG_LEVEL_SQL:DEBUG}
        type:
          descriptor:
            sql:
              BasicBinder: ${LOG_LEVEL_SQL_BINDER:TRACE}

webhook:
  slack:
    url: ${WEBHOOK_SLACK_URL}

message:
  sender: ${MESSAGE_SENDER:02-1234-5678}

auth:
  google:
    client-id: ${GOOGLE_CLIENT_ID:88628206428-0m206hm81hfff14e5v6d5tgsmbnrbo9g.apps.googleusercontent.com}
    client-secret: ${GOOGLE_CLIENT_SECRET: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}
    token-uri: ${GOOGLE_TOKEN_URI:https://oauth2.googleapis.com/token}
    userinfo-uri: ${GOOGLE_USERINFO_URI:https://www.googleapis.com/oauth2/v2/userinfo}

  kakao:
    restapi-key: ${KAKAO_RESTAPI_KEY:f9ef71c243f291c800012839d6ad7340}
    token-uri: ${KAKAO_TOKEN_URI:https://kauth.kakao.com/oauth/token}
    user-info-uri: ${KAKAO_USERINFO_URI:https://kapi.kakao.com/v2/user/me}

  naver:
    client-id: ${NAVER_CLIENT_ID:uuQR8vP5VQLKCdaaxQB4}
    client-secret: ${NAVER_CLIENT_SECRET:giFLLT7_aF}
    token-uri: ${NAVER_TOKEN_URI:https://nid.naver.com/oauth2.0/token}
    user-info-uri: ${NAVER_USERINFO_URI:https://openapi.naver.com/v1/nid/me}

  apple:
    client-id: ${APPLE_CLIENT_ID:im.fooding.loginservice}
    team-id: ${APPLE_TEAM_ID:4TS88K9HKJ}
    key-id: ${APPLE_KEY_ID:4PPY69KNW8}
    private-key: ${APPLE_PRIVATE_KEY:MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrHlqh7uGlOTNbxyBSeyyZ4JyLKNMDboPO+K4he/6URKgCgYIKoZIzj0DAQehRANCAASN1R+nHzVoAbh7kRGG4GBdlOAqZTWsvC4AaWjQl2osHTB7Vu2ctjTvKJTD6Col9dCt4eFTPSQyMX+7ezJyucy2}
    token-uri: ${APPLE_TOKEN_URI:https://appleid.apple.com/auth/token}
